include:
  - .requirements
  - apache
  - apache.vhosts.standard
  - .pear
  - .iksemel
  - .dahdi
  - .libpri
  - .pjproject
  - .jansson
  - .asterisk
  - .asterisk-extra-sounds
  - .cleanup
  - .freepbx